import type { AndroidSymbol } from 'expo-symbols';
import type { SFSymbol } from 'sf-symbols-typescript';

export type IconName = SFSymbol;

const map: Record<string, AndroidSymbol> = {
  archivebox: 'archive',
  'arrow.up': 'arrow_upward',
  'arrow.down.left': 'arrow_downward',
  'arrow.up.right': 'arrow_forward',
  'bell.slash': 'notifications_off',
  'bell.badge': 'notifications',
  'bubble.left': 'chat',
  'bubble.left.and.bubble.right': 'forum',
  calendar: 'event',
  checkmark: 'check',
  'checkmark.circle': 'check_circle',
  'checkmark.circle.fill': 'check_circle',
  'chevron.left': 'chevron_left',
  'chevron.right': 'chevron_right',
  clock: 'schedule',
  doc: 'description',
  ellipsis: 'more_horiz',
  gearshape: 'settings',
  link: 'link',
  'lock.shield': 'shield',
  magnifyingglass: 'search',
  megaphone: 'campaign',
  mic: 'mic',
  pencil: 'edit',
  'person.crop.circle': 'account_circle',
  phone: 'call',
  'phone.badge.plus': 'add_call',
  photo: 'image',
  'photo.on.rectangle': 'photo_library',
  pin: 'push_pin',
  'play.fill': 'play_arrow',
  'play.rectangle': 'play_circle',
  plus: 'add',
  qrcode: 'qr_code',
  sparkles: 'auto_awesome',
  'square.and.pencil': 'edit_square',
  'square.grid.2x2': 'grid_view',
  video: 'videocam',
  xmark: 'close',
  'xmark.circle.fill': 'cancel',
  at: 'alternate_email',
  camera: 'photo_camera',
  'chart.bar': 'bar_chart',
  'circle.lefthalf.filled': 'contrast',
  envelope: 'mail',
  'info.circle': 'info',
  internaldrive: 'storage',
  'laptopcomputer.and.iphone': 'devices',
  location: 'place',
  moon: 'dark_mode',
  'questionmark.circle': 'help',
  'sun.max': 'light_mode',
  trash: 'delete',
  'exclamationmark.triangle': 'warning',
  nosign: 'block',
  'rectangle.portrait.and.arrow.right': 'logout',
  tray: 'inbox',
  'text.quote': 'format_quote',
};

export function toAndroidSymbol(name: IconName): AndroidSymbol {
  return map[name] ?? 'circle';
}
